// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soaonapntsktpqoqptyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYW9uYXBudHNrdHBxb3FwdHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzgzNDAsImV4cCI6MjA1NzQxNDM0MH0.hN2AeKcjJd94-O_egMln3VlBgpDmpv8gasLNhrnH4w4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);